using System.Text;
using CityBuilder.Ecs;
using CityBuilder.Ecs.Components;
using CityBuilder.Economy;
using CityBuilder.Grid;
using CityBuilder.Networks;
using CityBuilder.Utilities;
using CityBuilder.Zoning;

namespace CityBuilder.Persistence;

/// <summary>
/// Binary snapshot of the simulation's PERSISTENT state: config, clock, RNG, terrain, zoning,
/// heat-maps, networks, utility grids, economy and buildings. Hand-rolled field-by-field IO
/// (no reflection, no struct-layout assumptions, no external packages) keeps the format
/// deterministic and netstandard2.1-portable.
/// <para>
/// TRANSIENT state is deliberately not saved: vehicles in flight, route buffers and edge
/// congestion are regenerated by their systems after load (the standard city-builder approach),
/// and market prices/utility reports are recomputed on the next economic tick.
/// </para>
/// <para>
/// Loading is a rebuild: construct a fresh <see cref="GameSimulation"/> from
/// <see cref="ReadConfig"/>, run the same host bootstrap as a new game (definitions + scenario
/// systems — but NOT world content), then call <see cref="ReadInto"/> positioned at the start
/// of the save. Buildings are re-created through the factory, so load emits the same
/// construction events a live game would — the view rebuilds itself by observing.
/// </para>
/// </summary>
public static class SaveGame
{
    // v2: config carries city name + terrain preset, and a fast METADATA block (population,
    // treasury, tick, saved-at) sits before the state so the Load City screen can list saves
    // without deserialising whole worlds.
    private const int Version = 2;
    private static readonly byte[] Magic = { (byte)'C', (byte)'B', (byte)'S', (byte)'V' };

    // Fixed enumeration orders so the byte stream never depends on dictionary ordering.
    private static readonly HeatMapKind[] HeatMapKinds =
    {
        HeatMapKind.Desirability, HeatMapKind.LandValue, HeatMapKind.Pollution,
        HeatMapKind.Crime, HeatMapKind.TrafficNoise, HeatMapKind.ServiceCoverage,
    };

    private static readonly NetworkType[] NetworkTypes =
    {
        NetworkType.Road, NetworkType.Rail, NetworkType.WaterPipe,
        NetworkType.PowerLine, NetworkType.Sewage,
    };

    public static void Write(GameSimulation sim, Stream stream)
    {
        using var w = new BinaryWriter(stream, Encoding.UTF8, leaveOpen: true);

        w.Write(Magic);
        w.Write(Version);

        // Config.
        w.Write(sim.Config.Width);
        w.Write(sim.Config.Height);
        w.Write(sim.Config.Seed);
        w.Write(sim.Config.TicksPerSecond);
        w.Write(sim.Config.CityName ?? "New City"); // a default-constructed config has a null name
        w.Write((byte)sim.Config.Terrain);

        // Metadata block (Load City screen reads only this far).
        w.Write(ZoningStats.Population(sim.Map.Zoning));
        w.Write(sim.Economy.Balance.Units);
        w.Write(sim.CurrentTick);
        w.Write(DateTime.UtcNow.Ticks); // wall-clock label only — never used by the simulation

        // Clock + RNG.
        w.Write(sim.CurrentTick);
        w.Write(sim.Random.State);

        // Terrain.
        Span<TerrainCell> terrain = sim.Map.Terrain.AsSpan();
        for (int i = 0; i < terrain.Length; i++)
        {
            w.Write(terrain[i].Elevation);
            w.Write((byte)terrain[i].Kind);
            w.Write(terrain[i].Flags);
        }

        // Zoning.
        Span<ZoneCell> zoning = sim.Map.Zoning.AsSpan();
        for (int i = 0; i < zoning.Length; i++)
        {
            w.Write((byte)zoning[i].Type);
            w.Write((byte)zoning[i].Density);
            w.Write(zoning[i].DevelopmentLevel);
            w.Write(zoning[i].Occupancy);
        }

        // Heat-maps (fixed kind order; absent maps marked with a flag).
        for (int k = 0; k < HeatMapKinds.Length; k++)
        {
            bool exists = sim.HeatMaps.TryGet(HeatMapKinds[k], out HeatMap map);
            w.Write(exists);
            if (!exists)
            {
                continue;
            }

            Span<float> field = map.Field.AsSpan();
            for (int i = 0; i < field.Length; i++)
            {
                w.Write(field[i]);
            }
        }

        // Networks (nodes then raw directed edges, both in id order, so ids survive round-trip).
        for (int t = 0; t < NetworkTypes.Length; t++)
        {
            FlowNetwork net = sim.GetNetwork(NetworkTypes[t]);
            w.Write(net.NodeCount);
            for (int n = 0; n < net.NodeCount; n++)
            {
                GridCoord c = net.GetCoord(n);
                w.Write(c.X);
                w.Write(c.Y);
            }

            w.Write(net.EdgeCount);
            for (int e = 0; e < net.EdgeCount; e++)
            {
                NetworkEdge edge = net.GetEdge(new EdgeId(e));
                w.Write(edge.From.Value);
                w.Write(edge.To.Value);
                w.Write(edge.BaseCost);
                w.Write(edge.Capacity);
            }
        }

        // Utility grids (their networks were saved above; here only sources/consumers/tuning).
        w.Write(sim.Utilities.Grids.Count);
        for (int g = 0; g < sim.Utilities.Grids.Count; g++)
        {
            UtilityGrid grid = sim.Utilities.Grids[g];
            w.Write((byte)grid.Kind);
            w.Write(grid.MaxServiceDistance);

            w.Write(grid.Sources.Count);
            for (int i = 0; i < grid.Sources.Count; i++)
            {
                w.Write(grid.Sources[i].Node.Value);
                w.Write(grid.Sources[i].Capacity);
            }

            w.Write(grid.Consumers.Count);
            for (int i = 0; i < grid.Consumers.Count; i++)
            {
                w.Write(grid.Consumers[i].Node.Value);
                w.Write(grid.Consumers[i].Demand);
            }
        }

        // Economy: treasury + tax policy (markets/reports are recomputed next tick).
        w.Write(sim.Economy.Balance.Units);
        w.Write(sim.Economy.Taxes.GetRate(ZoneType.Residential));
        w.Write(sim.Economy.Taxes.GetRate(ZoneType.Commercial));
        w.Write(sim.Economy.Taxes.GetRate(ZoneType.Industrial));

        // Buildings: (definition id, cell, level) — recreated through the factory on load.
        ComponentStore<BuildingComponent> buildings = sim.Entities.Store<BuildingComponent>();
        w.Write(buildings.Count);
        Span<BuildingComponent> comps = buildings.Components;
        ReadOnlySpan<Entity> owners = buildings.Owners;
        for (int i = 0; i < comps.Length; i++)
        {
            GridPositionComponent pos = sim.Entities.Get<GridPositionComponent>(owners[i]);
            w.Write(sim.Definitions.GetByIndex(comps[i].DefinitionIndex).Id);
            w.Write(pos.Cell.X);
            w.Write(pos.Cell.Y);
            w.Write(pos.Elevation);
            w.Write(comps[i].Level);
        }
    }

    /// <summary>
    /// Read just the header + config from a save (stream positioned at its start), so the host
    /// can construct the matching <see cref="GameSimulation"/> before calling <see cref="ReadInto"/>.
    /// </summary>
    public static GameConfig ReadConfig(Stream stream)
    {
        using var r = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);
        ReadHeader(r);
        return ReadConfigBody(r);
    }

    /// <summary>
    /// Read the cheap metadata for the Load City screen (stream positioned at the save's start):
    /// name, size, population, treasury, game date and when it was saved — without touching the
    /// world state that follows.
    /// </summary>
    public static SaveMetadata ReadMetadata(Stream stream)
    {
        using var r = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);
        ReadHeader(r);
        GameConfig config = ReadConfigBody(r);

        long population = r.ReadInt64();
        var treasury = new Money(r.ReadInt64());
        long tick = r.ReadInt64();
        var savedAtUtc = new DateTime(r.ReadInt64(), DateTimeKind.Utc);

        return new SaveMetadata(config, population, treasury, tick, savedAtUtc);
    }

    /// <summary>
    /// Restore a full snapshot into a freshly constructed, bootstrapped simulation. The stream
    /// must be positioned at the START of the save (the header is re-read and re-verified).
    /// </summary>
    public static void ReadInto(GameSimulation sim, Stream stream)
    {
        using var r = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);
        ReadHeader(r);
        GameConfig config = ReadConfigBody(r);

        if (config.Width != sim.Config.Width || config.Height != sim.Config.Height || config.Seed != sim.Config.Seed)
        {
            throw new InvalidOperationException(
                "Save/simulation config mismatch: construct the simulation from SaveGame.ReadConfig(...) first.");
        }

        // Skip the metadata block (display-only; the state that follows is authoritative).
        r.ReadInt64(); // population
        r.ReadInt64(); // treasury units
        r.ReadInt64(); // tick
        r.ReadInt64(); // saved-at utc

        // Clock + RNG.
        sim.Clock.Restore(r.ReadInt64());
        sim.Random.State = r.ReadUInt64();

        // Terrain.
        Span<TerrainCell> terrain = sim.Map.Terrain.AsSpan();
        for (int i = 0; i < terrain.Length; i++)
        {
            terrain[i].Elevation = r.ReadInt16();
            terrain[i].Kind = (TerrainKind)r.ReadByte();
            terrain[i].Flags = r.ReadByte();
        }

        // Zoning.
        Span<ZoneCell> zoning = sim.Map.Zoning.AsSpan();
        for (int i = 0; i < zoning.Length; i++)
        {
            zoning[i].Type = (ZoneType)r.ReadByte();
            zoning[i].Density = (ZoneDensity)r.ReadByte();
            zoning[i].DevelopmentLevel = r.ReadByte();
            zoning[i].Occupancy = r.ReadByte();
        }

        // Heat-maps.
        for (int k = 0; k < HeatMapKinds.Length; k++)
        {
            if (!r.ReadBoolean())
            {
                continue;
            }

            Span<float> field = sim.HeatMaps.GetOrCreate(HeatMapKinds[k]).Field.AsSpan();
            for (int i = 0; i < field.Length; i++)
            {
                field[i] = r.ReadSingle();
            }
        }

        // Networks — the target must be pristine so re-added nodes/edges keep their saved ids.
        for (int t = 0; t < NetworkTypes.Length; t++)
        {
            FlowNetwork net = sim.GetNetwork(NetworkTypes[t]);
            if (net.NodeCount != 0)
            {
                throw new InvalidOperationException(
                    $"Cannot load into a simulation whose {NetworkTypes[t]} network already has content.");
            }

            int nodeCount = r.ReadInt32();
            for (int n = 0; n < nodeCount; n++)
            {
                int x = r.ReadInt32();
                int y = r.ReadInt32();
                net.AddNode(new GridCoord(x, y));
            }

            int edgeCount = r.ReadInt32();
            for (int e = 0; e < edgeCount; e++)
            {
                var from = new NodeId(r.ReadInt32());
                var to = new NodeId(r.ReadInt32());
                float cost = r.ReadSingle();
                int capacity = r.ReadInt32();

                // Edges were saved as raw directed entries; re-adding one-way in the same
                // order reproduces identical edge ids.
                net.Connect(from, to, cost, capacity, bidirectional: false);
            }
        }

        // Utility grids.
        int gridCount = r.ReadInt32();
        for (int g = 0; g < gridCount; g++)
        {
            var kind = (NetworkType)r.ReadByte();
            UtilityGrid grid = sim.CreateUtility(kind);
            grid.MaxServiceDistance = r.ReadSingle();

            int sourceCount = r.ReadInt32();
            for (int i = 0; i < sourceCount; i++)
            {
                var node = new NodeId(r.ReadInt32());
                grid.AddSource(node, r.ReadSingle());
            }

            int consumerCount = r.ReadInt32();
            for (int i = 0; i < consumerCount; i++)
            {
                var node = new NodeId(r.ReadInt32());
                grid.AddConsumer(node, r.ReadSingle());
            }
        }

        // Economy.
        sim.Economy.RestoreBalance(new Money(r.ReadInt64()));
        sim.Economy.Taxes.SetRate(ZoneType.Residential, r.ReadSingle());
        sim.Economy.Taxes.SetRate(ZoneType.Commercial, r.ReadSingle());
        sim.Economy.Taxes.SetRate(ZoneType.Industrial, r.ReadSingle());

        // Buildings — recreated via the factory so construction events fire for the view.
        int buildingCount = r.ReadInt32();
        for (int i = 0; i < buildingCount; i++)
        {
            string definitionId = r.ReadString();
            int x = r.ReadInt32();
            int y = r.ReadInt32();
            int elevation = r.ReadInt32();
            byte level = r.ReadByte();

            Entity building = sim.Factory.CreateBuilding(definitionId, new GridCoord(x, y));
            sim.Entities.Get<GridPositionComponent>(building).Elevation = elevation;
            sim.Entities.Get<BuildingComponent>(building).Level = level;
        }
    }

    private static void ReadHeader(BinaryReader r)
    {
        byte[] magic = r.ReadBytes(4);
        if (magic.Length != 4 || magic[0] != Magic[0] || magic[1] != Magic[1] || magic[2] != Magic[2] || magic[3] != Magic[3])
        {
            throw new InvalidDataException("Not a CityBuilder save file.");
        }

        int version = r.ReadInt32();
        if (version != Version)
        {
            throw new InvalidDataException($"Unsupported save version {version} (expected {Version}).");
        }
    }

    private static GameConfig ReadConfigBody(BinaryReader r)
    {
        int width = r.ReadInt32();
        int height = r.ReadInt32();
        ulong seed = r.ReadUInt64();
        double ticksPerSecond = r.ReadDouble();
        string cityName = r.ReadString();
        var terrain = (TerrainPreset)r.ReadByte();
        return new GameConfig(width, height, seed, ticksPerSecond, cityName, terrain);
    }
}
